### ISSUE TITLE
ERROR: 'ImportFrom' object has no attribute 'end_lineno'

### ISSUE THREAD

**Issue by AndreyNvk** [K1DV5/docal#25]
Hello,

Just tried to run docal, installed it in my vitrual env, copypasted example from readme, executed the `docal foo.py -o foo.docx` but got the error:
`ERROR: 'ImportFrom' object has no attribute 'end_lineno'`
That's everything I got, have no idea why I got this error and how I can fix it

I'm using ubuntu 18.04.5 LTS and python 3.7
The only thing installed in my venv is
`docal==3.0.1`

Could you please help me find out what I'm doing wrong?

**Comment by sparry0407** [comment]
I have the same problem, using docal_tkinter...

**Comment by sparry0407** [comment]
Worked it out - you need Python 3.8.6 minimum, otherwise boom.

**Comment by K1DV5** [comment]
@AndreyNvk sorry I didn't specify the supported versions. @sparry0407 glad you figured it out! I have added a note about that and made the classifiers specific.
