### ISSUE TITLE
docal doesnt show up in a mathcad search

### ISSUE THREAD

**Issue by coburnw** [K1DV5/docal#27]
Hi Kidus

Hardly an issue but... I would like to suggest that you add a mathcad tag of some sort that allows the docal repository to be found when doing a github search for mathcad.  Docal is a very good alternative for those of us who are unwilling or unable to pony up to mathcad. I spent a lot of time going down the sympy rabbit hole before finally finding this repository via a duckduck search.

In other words, Thank you.
c.

**Comment by K1DV5** [comment]
Done, thank you!
